# Generated by Django 4.1.7 on 2023-02-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('fechaCosecha', models.DateField()),
                ('paseCosecha', models.TextField()),
                ('areaFrascosCosecha', models.IntegerField()),
                ('numFrascosCosecha', models.IntegerField()),
                ('numCelulasObtenidas', models.FloatField()),
                ('viabilidadCosecha', models.IntegerField()),
                ('idCosecha', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
