# Generated by Django 4.1.7 on 2023-02-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCelulasXVial', models.FloatField()),
                ('numViales', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cosecha',
            name='loteCosecha',
            field=models.TextField(default='000'),
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loteSimbra', models.TextField()),
                ('fechaSiembra', models.DateField()),
                ('paseSiembra', models.TextField()),
                ('areaFrascosSiembra', models.IntegerField()),
                ('numFrascosSiembra', models.IntegerField()),
                ('numCelulasSembradasXFrasco', models.FloatField()),
                ('cosechaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.cosecha')),
            ],
        ),
    ]
