# Generated by Django 4.1.7 on 2023-02-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_alter_cosecha_lotecosecha_alter_cosecha_pasecosecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='areaFrascosCosecha',
            field=models.IntegerField(choices=[(25, 'T25'), (75, 'T75'), (175, 'T175'), (850, 'CR Liso'), (2125, 'CR Corrugado'), (0, 'Crioviales')]),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='loteCosecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='paseCosecha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siembra',
            name='areaFrascosSiembra',
            field=models.IntegerField(choices=[(25, 'T25'), (75, 'T75'), (175, 'T175'), (850, 'CR Liso'), (2125, 'CR Corrugado'), (0, 'Crioviales')]),
        ),
        migrations.AlterField(
            model_name='siembra',
            name='loteSimbra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siembra',
            name='paseSiembra',
            field=models.CharField(max_length=50),
        ),
    ]
