# Generated by Django 4.1.7 on 2023-02-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_alter_crio_cosechafkcrio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crio',
            name='cosechaFKCrio',
        ),
    ]
