# Generated by Django 4.1.7 on 2023-02-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_rename_cosechafksiembra_siembra_cosechafk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siembra',
            old_name='cosechaFK',
            new_name='cosechaFKSiembra',
        ),
        migrations.AddField(
            model_name='crio',
            name='cosechaFKCrio',
            field=models.ForeignKey(default='01-01-2000-25-001', on_delete=django.db.models.deletion.CASCADE, to='formularios.cosecha'),
        ),
    ]
