# Generated by Django 4.1.7 on 2023-02-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_rename_cosechafk_siembra_cosechafksiembra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crio',
            name='cosechaFKCrio',
            field=models.ForeignKey(default='01-01-2000-25-1-001', on_delete=django.db.models.deletion.CASCADE, to='formularios.cosecha'),
        ),
    ]
