# Generated by Django 4.1.7 on 2023-02-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_cosecha_cci_crio_cci_siembra_cci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='cci',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='crio',
            name='cci',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='siembra',
            name='cci',
            field=models.CharField(default='', max_length=10),
        ),
    ]
