# Generated by Django 4.1.7 on 2023-02-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0014_alter_cosecha_fechacosecha_alter_cosecha_pasecosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='crio',
            name='totalCrio',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
