# Generated by Django 4.1.7 on 2023-02-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_crio_totalcrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='siembra',
            name='densidadSiembra',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
