# Generated by Django 4.1.7 on 2023-02-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0016_siembra_densidadsiembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='densidadCosecha',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
