# Generated by Django 4.1.7 on 2023-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0017_cosecha_densidadcosecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siembra',
            name='paseSiembra',
            field=models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7')], max_length=10),
        ),
    ]
