# Generated by Django 4.1.7 on 2023-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0018_alter_siembra_pasesiembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='confluenciaCosecha',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosecha',
            name='tiempoCultivoDias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
