# Generated by Django 4.1.7 on 2023-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0021_remove_cosecha_idcosecha_remove_crio_cosechafkcrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siembra',
            name='totalSiembra',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
