# Generated by Django 4.1.7 on 2023-02-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0022_siembra_totalsiembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='totalObtenidas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
