# Generated by Django 4.1.7 on 2023-02-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0023_cosecha_totalobtenidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosecha',
            name='id',
        ),
        migrations.AddField(
            model_name='cosecha',
            name='cosehaId',
            field=models.CharField(default='C0120001-2000-01-01-25-01-001', max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
