# Generated by Django 4.1.7 on 2023-02-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0024_remove_cosecha_id_cosecha_cosehaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cosecha',
            old_name='cosehaId',
            new_name='cosechaId',
        ),
    ]
