# Generated by Django 4.1.7 on 2023-02-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0025_rename_cosehaid_cosecha_cosechaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generaciones', models.FloatField()),
                ('tiempoDuplicacion', models.FloatField()),
                ('relacionExpansion', models.FloatField()),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.cosecha')),
                ('siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.siembra')),
            ],
        ),
    ]
