# Generated by Django 4.1.5 on 2023-03-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0026_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='crio',
            name='cosecha',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='formularios.cosecha'),
            preserve_default=False,
        ),
    ]
