# Generated by Django 4.1.5 on 2023-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0029_dato_lotedatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='loteDatos',
            field=models.IntegerField(default=0),
        ),
    ]
