# Generated by Django 4.1.5 on 2023-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0031_alter_dato_lotedatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='densidadCosecha',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name='dato',
            name='densidadSiembra',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
