# Generated by Django 4.2.3 on 2023-08-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0032_dato_densidadcosecha_dato_densidadsiembra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crio',
            name='id',
        ),
        migrations.AddField(
            model_name='crio',
            name='crioId',
            field=models.CharField(default='criox', max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
