# Generated by Django 4.2.3 on 2023-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0033_remove_crio_id_crio_crioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crio',
            name='crioId',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
