# Generated by Django 4.2.3 on 2023-08-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0035_alter_crio_crioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='pase',
            field=models.CharField(default='000', max_length=50),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='areaFrascosCosecha',
            field=models.IntegerField(choices=[(25, 'T25'), (75, 'T75'), (175, 'T175'), (850, 'CR Liso'), (2125, 'CR Corrugado'), (1272, 'CS 2p'), (3180, 'CS 5p'), (6360, 'CS 10p'), (500, 'TripleFlask'), (0, 'Crioviales')]),
        ),
        migrations.AlterField(
            model_name='siembra',
            name='areaFrascosSiembra',
            field=models.IntegerField(choices=[(25, 'T25'), (75, 'T75'), (175, 'T175'), (850, 'CR Liso'), (2125, 'CR Corrugado'), (1272, 'CS 2p'), (3180, 'CS 5p'), (6360, 'CS 10p'), (500, 'TripleFlask'), (0, 'Crioviales')]),
        ),
    ]
