# Generated by Django 4.2.3 on 2023-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0036_dato_pase_alter_cosecha_areafrascoscosecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='datoId',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
