# Generated by Django 4.2.3 on 2023-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0037_dato_datoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato',
            name='id',
        ),
        migrations.AlterField(
            model_name='dato',
            name='datoId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
