# Generated by Django 4.2.3 on 2023-08-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0038_remove_dato_id_alter_dato_datoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='siembra',
            name='medioSiembra',
            field=models.CharField(default='NR', max_length=10),
        ),
    ]
