# Generated by Django 4.2.3 on 2023-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0039_siembra_mediosiembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='medioSiembra',
            field=models.CharField(default='NR', max_length=10),
        ),
    ]
