# Generated by Django 4.2.3 on 2023-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0040_dato_mediosiembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='crio',
            name='fechaCrio',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
