# Generated by Django 4.2.3 on 2023-08-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0041_crio_fechacrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crio',
            name='fechaCrio',
            field=models.DateField(),
        ),
    ]
