# Generated by Django 4.2.3 on 2023-08-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0042_alter_crio_fechacrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='medioSiembra',
            field=models.CharField(default='NR', max_length=50),
        ),
    ]
