# Generated by Django 4.2.7 on 2024-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formularios", "0044_alter_siembra_mediosiembra"),
    ]

    operations = [
        migrations.AddField(
            model_name="dato",
            name="comentarios",
            field=models.CharField(default="", max_length=100),
        ),
    ]
